version: '2.1'

services:
  physics_mariadb_102:
    image: mariadb:10.2
    volumes:
      - physics_mariadb_102_volume:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: always
    container_name: physics_mariadb_102

  phpmyadminPhysics:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: physics_mariadb_102
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    restart: always
    ports:
      - "9092:80"
    container_name: phpmyadminPhysics
    depends_on:
      - physics_mariadb_102

  physics_backend:
    image: node:12.14
    volumes:
      - ./:/home/node
    working_dir: /home/node
    command: bash -c "npm start"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - physics_mariadb_102
    container_name: physics_backend

volumes:
  physics_mariadb_102_volume:
